{% set name = "google-cloud-resource-manager" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-resource-manager-{{ version }}.tar.gz
  sha256: 6cf8a9a74e65a03857896967c79307b75805c752ade3bc41224e6167774bc9c9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - grpc-google-iam-v1 >=0.12.4,<1.0.0dev
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.20.2,<5.0.0dev

test:
  imports:
    - grpc
    - google.cloud.resourcemanager
    - google.cloud.resourcemanager_v3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-resource-manager
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Resource Manager API client library
  description: "Google Cloud Resource Manager API provides methods that you can use to programmatically manage your projects in the Google Cloud Platform. You can create, list, update or delete projects within Google Cloud Platform.\nSee the [quick start guide](https://googleapis.dev/python/cloudresourcemanager/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/cloudresourcemanager/latest/index.html
  dev_url: https://github.com/googleapis/python-resource-manager

extra:
  recipe-maintainers:
    - xylar
    - parthea
