{% set name = "google-cloud-resource-manager" %}
{% set version = "1.3.2" %}
{% set sha256 = "b99e11360668ed0c034c8cf3a34caf6fd4a52efaf62d54dd85407c3ad20b715c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
    - google-api-core-grpc >=1.26.0,<3.0.0dev
    - proto-plus >=1.15.0
    - packaging >=14.3
    - grpc-google-iam-v1 >=0.12.3,<0.13dev
  run:
    - python >=3.6
    - google-api-core-grpc
    - proto-plus
    - packaging
    - grpc-google-iam-v1

test:
  imports:
    - grpc
    - google.cloud.resourcemanager
    - google.cloud.resourcemanager_v3

about:
  home: https://github.com/googleapis/python-resource-manager
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Resource Manager API client library
  description: "Google Cloud Resource Manager API provides methods that you can use to programmatically manage your projects in the Google Cloud Platform. You can create, list, update or delete projects within Google Cloud Platform.\nSee the [quick start guide](https://googleapis.dev/python/cloudresourcemanager/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/cloudresourcemanager/latest/index.html
  dev_url: https://github.com/googleapis/python-resource-manager

extra:
  recipe-maintainers:
    - parthea
